unit Mir3ServerConstants;

interface

const

  (* Run Gate things *)
  MIR3_MAX_GATE                     = 20;
  MIR3_MAX_GATE_SESSION             = 10000;
  MIR3_MAX_PUBLIC_ADDR              = 30;
  MIR3_STATUS_ARRAY_SIZE            = 16;
  MIR3_SEND_BLOCK                   = 1024;
  MIR3_SEND_CHECK_BLOCK             = 4096;
  MIR3_SEND_AVAILABLE_BLOCK         = 7999;
  MIR3_DEFAULT_BLOCK_SIZE           = 16;
  MIR3_MAX_QUEST_INDEX_BYTE         = 24;
  MIR3_MAX_QUEST_BYTE               = 176;
  MIR3_NON_PK_LEVEL                 = 10;
  MIR3_MAX_BAG_ITEM                 = 46;
  MIR3_MAX_HORSE_BAG                = 30;
  MIR3_MAX_PET_BAG                  = 20;

  GM_OPEN                           = 1;
  GM_CLOSE                          = 2;
  GM_CHECK_SERVER                   = 3;
  GM_CHECK_CLIENT                   = 4;
  GM_DATA                           = 5;
  GM_SERVER_USER_INDEX              = 6;
  GM_RECEIVE_OK                     = 7;
  GM_TEST                           = 20;

  ISM_PASSWORD_SUCCESS              = 100;
  ISM_CANCEL_ADMISSION              = 101;
  ISM_USER_CLOSED                   = 102;
  ISM_USER_COUNT                    = 103;
  ISM_TOTAL_USER_COUNT              = 104;
  ISM_SHIFTVENTURESERVER            = 110;
  ISM_ACCOUNT_EXPIRED               = 111;
  ISM_GAMETIMEOFTIMECARDUSER        = 112;
  ISM_USAGE_INFORMATION             = 113;
  ISM_FUNC_USER_OPEN                = 114;
  ISM_FUNC_USER_CLOSE               = 115;
  ISM_CHECKTIMEACCOUNT              = 116;

  (* Item Description *)
  IDC_UN_IDENTIFIED                 = $01;
  IDC_UNABLE_TAKE_OFF               = $02;
  IDC_NEVER_TAKE_OFF                = $04;
  IDC_DIE_AND_BREAK                 = $08;
  IDC_NEVER_LOSE                    = $10;

  SM_OUTOFCONNECTION                = 528;

  U_DRESS                           = 0;
  U_WEAPON                          = 1;
  U_RIGHTHAND                       = 2;
  U_NECKLACE                        = 3;
  U_HELMET                          = 4;
  U_ARMRINGL                        = 5;
  U_ARMRINGR                        = 6;
  U_RINGL                           = 7;
  U_RINGR                           = 8;
  U_SHOE                            = 10;
  U_ROSE                            = 11;
  U_CHARM                           = 12;

  RM_TURN                           = 10001;
  RM_WALK                           = 10002;
  RM_RUN                            = 10003;
  RM_HIT                            = 10004;
  RM_HEAVYHIT                       = 10005;
  RM_BIGHIT                         = 10006;
  RM_SPELL                          = 10007;
  RM_POWERHIT                       = 10008;
  RM_SITDOWN                        = 10009;
  RM_MOVEFAIL                       = 10010;
  RM_LONGHIT                        = 10011;
  RM_WIDEHIT                        = 10012;
  RM_PUSH                           = 10013;
  RM_FIREHIT                        = 10014;
  RM_RUSH                           = 10015;
  RM_RUSHKUNG                       = 10016;
  RM_CROSSHIT                       = 10017;
  RM_TWINHIT                        = 10019;
  RM_DECREFOBJCOUNT                 = 10018;
  RM_STRUCK                         = 10020;
  RM_DEATH                          = 10021;
  RM_DISAPPEAR                      = 10022;
  RM_MAG_STRUCK_MINE                = 10028;
  RM_HEAR                           = 10030;
  RM_WHISPER                        = 10031;
  RM_CRY                            = 10032;
  RM_SYS_MESSAGE                    = 10100;
  RM_REFMESSAGE                     = 10101;
  RM_GROUPMESSAGE                   = 10102;
  RM_SYS_MESSAGE2                   = 10103;
  RM_GUILDMESSAGE                   = 10104;
  RM_SYS_MSG_BLUE                   = 10105;
  RM_SYS_MESSAGE3                   = 10106;
  RM_SYS_MSG_REMARK                 = 10107;
  RM_SYS_MSG_PINK                   = 10108;
  RM_SYS_MSG_GREEN                  = 10109;
  RM_MERCHANT_SAY                   = 10126;
  RM_MERCHANT_DLG_CLOSE             = 10127;
  RM_SEND_BUY_PRICE                 = 10130;
  RM_ALIVE                          = 10153;
  RM_MAKEPOISON                     = 10300;
  RM_CHANGEGUILDNAME                = 10301;
  RM_SUBABILITY                     = 10302;
  RM_BUILDGUILD_OK                  = 10303;
  RM_BUILDGUILD_FAIL                = 10304;
  RM_DONATE_FAIL                    = 10305;
  RM_DONATE_OK                      = 10306;
  RM_MYSTATUS                       = 10307;
  RM_TRANSPARENT                    = 10308;
  RM_MENU_OK                        = 10309;
  RM_SPACE_MOVE_HIDE                = 10330;
  RM_SPACE_MOVE_SHOW                = 10331;

  (* Skript Command Idents (QA) *)
  QA_SET                            = $1;
  QA_TAKE                           = $2;
  QA_GIVE                           = $3;
  QA_TAKEW                          = $4;
  QA_CLOSE                          = $5;
  QA_RESET                          = $6;
  QA_SETOPEN                        = $7;
  QA_SETUNIT                        = $8;
  QA_RESETUNIT                      = $9;
  QA_BREAK                          = $0A;
  QA_TIMERECALL                     = $0B;
  QA_PARAM1                         = $0C;
  QA_PARAM2                         = $0D;
  QA_PARAM3                         = $0E;
  QA_PARAM4                         = $0F;
  QA_MAPMOVE                        = $14;
  QA_MAP                            = $15;
  QA_TAKECHECKITEM                  = $16;
  QA_MONGEN                         = $17;
  QA_MONCLEAR                       = $18;
  QA_MONGENP                        = $19;
  QA_BREAKTIMERECALL                = $28;
  QA_GIVEW                          = $1A;
  QA_MOV                            = $1E;
  QA_INC                            = $1F;
  QA_DEC                            = $20;
  QA_SUM                            = $21;
  QA_DIV                            = $22;
  QA_MUL                            = $23;
  QA_PERCENT                        = $24;
  QA_MOD                            = $25;
  QA_MOVR                           = $32;
  QA_EXCHANGEMAP                    = $33;
  QA_RECALLMAP                      = $34;
  QA_ADDBATCH                       = $35;
  QA_BATCHDELAY                     = $36;
  QA_GIVEEX                         = $142;
  QA_GETCOORDINATES                 = $144;
  QA_TAKEEX                         = $147;
  QA_BATCHMOVE                      = $37;
  QA_PLAYDICE                       = $38;
  QA_PASTEMAP                       = $39;
  QA_LOADGEN                        = $3A;
  QA_GOTO                           = $66;
  QA_HAIRCOLOR                      = $68;
  QA_HAIRRNDCOL                     = $6D; //Random Hair Color
  QA_WEARCOLOR                      = $69;
  QA_HAIRSTYLE                      = $6A;
  QA_MONRECALL                      = $6B;
  QA_MONRECALLEX                    = $72;
  QA_CHANGESLAVELEVEL               = $145;
  QA_HORSECALL                      = $6C;
  QA_KILLHORSE                      = $85;
  QA_RANDSETDAILYQUEST              = $6E;
  QA_ADDNAMELIST                    = $6F;
  QA_DELNAMELIST                    = $70;
  QA_CLEARNAMELIST                  = $0EE;
  QA_REFINEWEAPON                   = $71;
  QA_GETREPAIRCOST                  = $86;
  QA_REPAIRITEM                     = $87;
  QA_RECALLGROUPMEMBERS             = $75;
  QA_MAPTING                        = $76;
  QA_WRITEWEAPONNAME                = $77;
  QA_WRITEWEAPONNAMEEX              = $143;
  QA_DELAYGOTO                      = $78;
  QA_ENABLECMD                      = $79;
  QA_SENDNOTICEMS                   = $141;
  QA_LINEMSG                        = $7A;
  QA_EVENTMSG                       = $7B;
  QA_SOUNDMSG                       = $7C;
  QA_SETMISSION                     = $7D;
  QA_CLEARMISSION                   = $7E;
  QA_MONPWR                         = $7F;
  QA_ENTER_OK                       = $80;
  QA_ENTER_FAIL                     = $81;
  QA_MONADDITEM                     = $82;
  QA_CHANGEWEATHER                  = $83;
  QA_CHANGEWEAPONATOM               = $84;
  QA_USEREMERGENCYCLOSE             = $8A;
  QA_BUILDGUILD                     = $8B;
  QA_GUILDWAR                       = $8C;
  QA_CHANGEMONLEVEL                 = $8E;
  QA_DROPITEMMAP                    = $8F;
  QA_CLEARITEMMAP                   = $0AA;
  QA_PROPOSECASTLEWAR               = $90;
  QA_FINISHCASTLEWAR                = $91;
  QA_MOVENPC                        = $92;
  QA_NPCNAMECHG                     = $135;
  QA_SPEAK                          = $93;
  QA_SENDCMD                        = $94;
  QA_INCFAME                        = $95;
  QA_DECFAME                        = $96;
  QA_CAPTURECASTLEFLAG              = $97;
  QA_MAKESHOOTER                    = $99;
  QA_KILLSHOOTER                    = $9A;
  QA_LEAVESHOOTER                   = $9B;
  QA_CHANGEMAPATTR                  = $9D;
  QA_RESETMAPATTR                   = $9E;
  QA_MAKECASTLEDOOR                 = $9F;
  QA_REPAIRCASTLEDOOR               = $0A0;
  QA_CHARGESHOOTER                  = $0A1;
  QA_SETAREAATTR                    = $0A2;
  QA_CLEARDELAYGOTO                 = $0A3;
  QA_TESTFLAG                       = $0A4;
  QA_APPLYFLAG                      = $0A5;
  QA_PASTEFLAG                      = $0A6;
  QA_GETBACKCASTLEGOLD              = $0A7;
  QA_GETBACKUPGITEM                 = $0A8;
  QA_TINGWAR                        = $0A9;
  QA_TINGCASTLEVISITOR              = $0EF;
  QA_SAVEPASSWD                     = $0AB;
  QA_CREATENPC                      = $0AC;
  QA_TAKEBONUS                      = $0AD;
  QA_SYSMSG                         = $0AE;
  QA_LOADVALUE                      = $0AF;
  QA_SAVEVALUE                      = $0B0;
  QA_SAVELOG                        = $0B1;
  QA_GETMARRIED                     = $0B2;
  QA_DIVORCE                        = $0BD;
  QA_CAPTURESAYING                  = $0BE;
  QA_CANCELMARRIAGERING             = $0BF;
  QA_OPENUSERMARKET                 = $0C0;
  QA_SETTYPEUSERMARKET              = $0C1;
  QA_CHECKSOLIDITEMSUSERMARKET      = $0C2;
  QA_CHECKSOLIDITEMSUSERPOINTMARKET = $138;
  QA_JOINGUILD                      = $0C3;
  QA_SETGMEMAP                      = $0C8;
  QA_SETGMEPOINT                    = $0C9;
  QA_SETGMETIME                     = $0D1;
  QA_STARTNEWGME                    = $0CA;
  QA_MOVETOGMEMAP                   = $0CB;
  QA_FINISHGME                      = $0CC;
  QA_CONTINUEGME                    = $0CD;
  QA_SETGMEPLAYTIME                 = $0CE;
  QA_SETGMEPAUSETIME                = $0CF;
  QA_SETGMELIMITUSER                = $0D0;
  QA_SETEVENTMAP                    = $0D2;
  QA_RESETEVENTMAP                  = $0D3;
  QA_TESTREFINEPOINTS               = $0DC;
  QA_RESETREFINEWEAPON              = $0DD;
  QA_TESTREFINEACCESSORIES          = $0DE;
  QA_REFINEACCESSORIES              = $0DF;
  QA_APPLYMONMISSION                = $0E1;
  QA_MAPMOVER                       = $0E2;
  QA_ADDSTR                         = $0E3;
  QA_DQSTR                          = $125;
  QA_SETEVENTDAMAGE                 = $0E4;
  QA_FORMATSTR                      = $0E5;
  QA_FORMATSTRSQL                   = $11E;
  QA_CLEARPAHT                      = $0E6;
  QA_ADDPLYPATH                     = $0E8;
  QA_MAPSPELL                       = $0E9;
  QA_GIVEEXP                        = $0EA;
  QA_GROUPMOVE                      = $0EB;
  QA_GIVEEXPMAP                     = $0EC;
  QA_APPLYMONEX                     = $0ED;
  QA_GIVEFAMEMAP                    = $126;
  QA_GETDATE                        = $127;
  QA_GETTIME                        = $128;
  QA_SPECIALREFINEWEAPON            = $12E;
  QA_CHECKSPECIALREFINE             = $12F;
  QA_GIVELIFE                       = $130;
  QA_RESURECTION                    = $140;
  QA_FIRECRACKERTOCHAR              = $132;
  QA_FIRECRACKERTOMAP               = $131;
  QA_GIVEUSERTITLEEX                = $146;
  QA_MAKEHEALZONE                   = $0F0;
  QA_MAKEDAMAGEZONE                 = $0F1;
  QA_CLEARZONE                      = $0F2;
  QA_READVALUESQL                   = $0FA;
  QA_READSTRINGSQL                  = $0FF;
  QA_READVALUESQLSYS                = $100;
  QA_READSTRINGSQLSYS               = $101;
  QA_WRITEVALUESQL                  = $0FB;
  QA_INCVALUESQL                    = $0FC;
  QA_DECVALUESQL                    = $0FD;
  QA_UPDATEVALUESQL                 = $0FE;
  QA_INITUSERALLQUEST               = $102;
  QA_KILLSLAVE                      = $104;
  QA_SETITEMEVENT                   = $105;
  QA_REMOVEITEMEVENT                = $106;
  QA_RETURN                         = $107;
  QA_CLEARCASTLEOWNER               = $10E;
  QA_DISSOLUTIONGUILD               = $10F;
  QA_CHANGEGENDER                   = $110;
  QA_SETFAME                        = $111;
  QA_TEAMMAKETEAM                   = $112;
  QA_MONTEAMMARK                    = $113;
  QA_MOVEMON                        = $114;
  QA_TEAMDIALOG                     = $115;
  QA_GROUPDIALOG                    = $116;
  QA_TEAMTING                       = $117;
  QA_TIMECALL                       = $118;
  QA_SETMAGEXTRA4                   = $119;
  QA_SETMAGEXTRA5                   = $11A;
  QA_MAKELOG                        = $11B;
  QA_MAKEITEMWLOG                   = $11C;
  QA_CLEARCASTLEGOLD                = $11D;
  QA_UPGRADEITEMNOW                 = $122;
  QA_BREAKWITEM                     = $123;
  QA_CHECKTEAMMEMBER                = $129;
  QA_INPUTTEAMMEMBER                = $12A;
  QA_DELETETEAMMEMBER               = $12C;
  QA_CHANGELEVEL                    = $12D;
  QA_SETTITLEABIL                   = $124;
  QA_OPENPOINTMARKET                = $136;
  QA_OPENUSERPOINTMARKET            = $137;
  QA_GETSYSINTTIMETO                = $148;
  QA_CHECKGUILDNUM                  = $149;
  QA_CLEARGUILD                     = $14A;
  QA_EXTENDITEMEXPIRETIME           = $14B;
  QA_RESURRECTIONMAP                = $14C;
  QA_RESURRECTIONGROUP              = $14D;
  QA_ADDUSERRAIDGROUP               = $14F;
  QA_SETRAIDGROUPOWNER              = $150;
  QA_BREAKRAIDGROUP                 = $151;
  QA_FILLUP                         = $152;
  QA_POISON                         = $153;
  QA_EMPOWER                        = $154;
  QA_GUILDNUM                       = $155;
  QA_GUILDMEMBERCLEAR               = $156;
  QA_MACROCHECK                     = $157;
  QA_TAKEWITEM                      = $158;
  QA_ATTENDATION                    = $159;
  QA_MAGICTYPECHANGE                = $15A;
  QA_GETMAGICCHANGE                 = $15B;
  QA_AUTOTING                       = $15C;
  QA_CHANGECHARSCALE                = $15D;
  QA_INCHEALTH                      = $15E;
  QA_OPENPETLISTBOX                 = $168;
  QA_OPENPETSHOP                    = $169;

  (* Skript Command Idents (QI) *)

  QI_CHECK                          = $1;
  QI_RANDOM                         = $2;
  QI_GENDER                         = $3;
  QI_DAYTIME                        = $4;
  QI_CHECKOPEN                      = $5;
  QI_CHECKUNIT                      = $6;
  QI_CHECKLEVEL                     = $7;
  QI_CHECKJOB                       = $8;
  QI_CHECKWEAPONLEVEL               = $31;
  QI_CHECKWEAPONATOM                = $32;
  QI_CHECKREFINEWEAPON              = $33;
  QI_CHECKWEAPONMCTYPE              = $34;
  QI_CHECKREFINEITEM                = $35;
  QI_HASWEAPONATOM                  = $36;
  QI_CHECKMONRECALL                 = $28;
  QI_CHECKMAGIC                     = $26;
  QI_CHECKMAGICLEVEL                = $27;
  QI_STARTDAILYQUEST                = $2D;
  QI_CHECKDAILYQUEST                = $2E;
  QI_CHECKDAILYQUESTUSER            = $74;
  QI_CHECKFLAG                      = $75;
  QI_CHECKGROUPMASTER               = $76;
  QI_RANDOMEX                       = $2F;
  QI_CHECKHORSE                     = $29;
  QI_CHECKRIDING                    = $2A;
  QI_CHECKITEM                      = $14;
  QI_CHECKITEMW                     = $15;
  QI_CHECKITEMEX                    = $54;
  QI_CHECKGOLD                      = $16;
  QI_ISTAKEITEM                     = $17;
  QI_CHECKDURA                      = $18;
  QI_CHECKDURAW                     = $70;
  QI_CHECKDURAEVA                   = $19;
  QI_DAYOFWEEK                      = $1A;
  QI_HOUR                           = $1B;
  QI_MIN                            = $1C;
  QI_CHECKPKPOINT                   = $1D;
  QI_CHECKMONMAP                    = $1F;
  QI_CHECKHUM                       = $21;
  QI_CHECKPOS                       = $47;
  QI_CHECKBAGGAGE                   = $22;
  QI_CHECKBAGSLOT                   = $81;
  QI_MOV                            = $51;
  QI_INC                            = $52;
  QI_DEC                            = $53;
  QI_EQUAL                          = $23;
  QI_LARGE                          = $24;
  QI_SMALL                          = $25;
  QI_ELARGE                         = $68;
  QI_ESMALL                         = $69;
  QI_CHECKNAMELIST                  = $30;
  QI_ISGUILDMASTER                  = $37;
  QI_HASGUILD                       = $44;
  QI_CANPROPOSECASTELEWAR           = $38;
  QI_CANHAVESHOOTER                 = $39;
  QI_CHECKFAME                      = $3A;
  QI_ISONCASTLEWAR                  = $3B;
  QI_ISONREADYCASTLEWAR             = $3C;
  QI_ISCASTLEGUILD                  = $3D;
  QI_ISATTACKGUILD                  = $3F;
  QI_ISDEFENSEGUILD                 = $41;
  QI_CHECKSHOOTER                   = $42;
  QI_CHECKSAVEDSHOOTER              = $43;
  QI_CHECKCASTLEDOOR                = $45;
  QI_CHECKCASTLEDOOROPEN            = $46;
  QI_CANCHARGESHOOTER               = $48;
  QI_ISATTACKALLGUILD               = $49;
  QI_TESTTEAM                       = $4B;
  QI_ISSYSOP                        = $4C;
  QI_ISADMIN                        = $4D;
  QI_CHECKBONUS                     = $4E;
  QI_CHECKMARRIAGE                  = $4F;
  QI_CHECKMARRIAGERING              = $50;
  QI_CHECKGMETERM                   = $64;
  QI_CHECKOPENGME                   = $65;
  QI_CHECKENTERGMEMAP               = $66;
  QI_CHECKSERVER                    = $67;
  QI_CHECKGROUPCOUNT                = $6A;
  QI_CHECKACCESSORY                 = $6B;
  QI_ONERROR                        = $6C;
  QI_CHECKARMOR                     = $6D;
  QI_CHECKCOMBACK                   = $77;
  QI_ISGUILDWAR                     = $78;
  QI_CHECKGUILDGROUP                = $79;
  QI_CHECKJOINGROUP                 = $7A;
  QI_CHECKTEAMCOUNT                 = $6E;
  QI_CHECKTEAM                      = $6F;
  QI_CHECKMAGEXTRA4                 = $71;
  QI_CHECKMAGEXTRA5                 = $72;
  QI_CHECKTITLE                     = $73;
  QI_CHECKALIVE                     = $7C;
  QI_CHECKSAVEITEMEX                = $7D;
  QI_CHECKWONBOITEM                 = $7E;
  QI_CHECKDESC                      = $7F;
  QI_CHECKPCROOM                    = $80;
  QI_CHECKCANMOVEMAP                = $82;
  QI_CHECKBCITEMW                   = $84;
  QI_CHECKDEMESNE                   = $85;

  (* Map Event Objects *)

  OS_MOVING_OBJECT                  = 1;
  OS_ITEM_OBJECT                    = 2;
  OS_EVENT_OBJECT                   = 3;
  OS_MAP_LINK_OBJECT                = 4;
  OS_SWITCH_OBJECT                  = 5;
  OS_MAP_EVENT                      = 6;
  OS_DROP_ITEM                      = 7;
  OS_PICKUP_ITEM                    = 8;

  (* Mine Events *)

  EVENT_MINE                        = 2;
  EVENT_MINE2                       = 8;
  EVENT_MINE3                       = 13;

  (* HAM - Human Attack Mode *)

  HAM_ALL                           = 0;
  HAM_PEACE                         = 1;
  HAM_GROUP                         = 2;
  HAM_GUILD                         = 3;
  HAM_PKATTACK                      = 4;
  HAM_MAXCOUNT                      = 5;

  (* MP - Map Param *)

  MP_CAN_MOVE                       = 0;
  MP_WALL			                      = 1;
  MP_HIGH_WALL                      = 2;

  NAME_OF_GOLD                      = 'Gold';
  MAX_GOLD                          = 2000000000;
  BAG_GOLD                          = 50000000;
  GROUP_MAX                         = 11;
  BODY_LUCK_UNIT                    = 5000;
  MAX_GUILD_MEMBER                  = 400;

  STDMODE_OF_DECOITEM               = 9;
  SHAPE_OF_DECOITEM                 = 1;

  UD_USER                           = 0;
  UD_USER2                          = 1;
  UD_OBSERVER                       = 2;
  UD_SYSOP                          = 3;
  UD_ADMIN                          = 4;
  UD_SUPERADMIN                     = 5;

  (* Race Type *)

  RACE_USER_HUMAN                   = 0;
  RACE_DOOR_GUARD                   = 11;
  RACE_PEACE_NPC                    = 15;
  RACE_CHICKEN                      = 31; //OK

  RACE_DEER                         = 52; //Pig, Deer, Cow , Sheep etc.
  RACE_WOLF                         = 53; //OK

  RACE_OMA_WAR                      = 81; //OK like OmaWarrior, ClawCat etc.
  RACE_SPIT_SPIDER                  = 82; //OK like SpittingSpider etc.
  RACE_SLOW_MONSTER                 = 83; //OK like Oma, Scarecrow etc.
  RACE_SCORPION                     = 84; //OK
  RACE_KILLING_HERB                 = 85; //OK like CarnivorousPlant etc.
  RACE_SKELETON                     = 86; //OK
  RACE_DUAL_AXE_SKELETON            = 87; //OK like SkeletonAxeThrower
  RACE_HEAVY_AXE_SKELETON           = 88; //OK like SkeletonAxeman
  RACE_KNIGHT_SKELETON              = 89; //OK like SkeletonWarrior
  RACE_GAS_ATTACK                   = 90; //OK like CaveMaggot
  RACE_MAG_COW_FACE_MON             = 91; //OK like UmaFlamethrower
  RACE_COW_FACE_KING_MON            = 92; //OK like UmaKing
  RACE_THORN_DARK                   = 93; //OK like SpinedDarkLizard
  RACE_LIGHTING_ZOMBI               = 94; //OK like GhostSorcerer

  RACE_ZILKIN_ZOMBI                 = 96; //OK like VoraciousGhost
  RACE_COW_MON                      = 97; //OK like Minotaur
  RACE_NUMA_GATE                    = 98; //OK like NumaGate
  RACE_SCULTURE_MON                 = 101; //OK like ZumaGuardian
  RACE_SCULTURE_KING                = 102; //OK like ZumaKing
  RACE_BEE_QUEEN                    = 103; //OK like WedgeMothLarva
  RACE_ARCHER_MON                   = 104; //OK like CannibalFanatic ,MutantFlea ,DevotedCultist
  RACE_GAS_MOTH                     = 105;
  RACE_DUNG                         = 106;
  RACE_CENTIPEDE_KING               = 107; //OK like LordJi'Nae
  RACE_CASTLE_DOOR_R                = 110; //OK GateofSabukKeep1 GateofSabukKeep2
  RACE_CASTLE_DOOR_L                = 111; //OK GateofSabukKeep3 GateofSabukKeep4
  RACE_SHINSU_STATE_1               = 113; //Shinsu
  RACE_SHINSU_STATE_2               = 114; //Shinsu 1

  RACE_SOCCERBALL                   = 120; //Football
  RACE_CATAPULT                     = 121; //OK Catapult
  RACE_BALLISTA                     = 122; //OK Ballista

  RACE_HORSE                        = 150; //OK YellowHorse, BrownHorse, WhiteHorse, RedHorse, BlackHorse, IronArmoredHorse....

  RACE_TREASURE_BOX                 = 199;

  RACE_MON_AI                       = 255;


  RACE_NPC                          = 10;

  RACE_ARCHERPOLICE                 = 20;
  RACE_ANIMAL                       = 50;
  RACE_MONSTER                      = 80;


  RACE_ARCHERMASTER                 = 161;

//  NAME="ChestnutTree" RACE="209"
implementation

end.
