DROP TABLE "M3_Account";

CREATE TABLE "M3_Account" (
	`FL_UserID`	INTEGER NOT NULL DEFAULT 0 PRIMARY KEY AUTOINCREMENT,
	`FL_UserName`	VARCHAR(100) NOT NULL UNIQUE,
	`FL_UserPassword`	VARCHAR(32) NOT NULL,
	`FL_Password_Backup`	VARCHAR(150),
	`FL_PassFailCount`	INTEGER DEFAULT 0,
	`FL_UserEMail`	VARCHAR(80) NOT NULL UNIQUE,
	`FL_TempBan`	BOOLEAN DEFAULT 0,
	`FL_PermBan`	BOOLEAN DEFAULT 0,
	`FL_Deleted`	BOOLEAN DEFAULT 0,
	`FL_TempBan_Start`	DATETIME DEFAULT CURRENT_TIMESTAMP,
	`FL_LastLogin`	DATETIME DEFAULT CURRENT_TIMESTAMP,
	`FL_DeletedDate`	DATETIME DEFAULT CURRENT_TIMESTAMP,
	`FL_MakeDateTime`	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)


INSERT INTO "M3_Account" (FL_UserID, FL_UserName, FL_UserPassword, FL_UserEMail) VALUES
                       (NULL, "Test", "0CBC6611F5540BD0809A388DC95A615B", "Test@Test.com");

